### ISSUE TITLE
feat: 有没有办法屏蔽列表回答视图中的相关问题回答和盐选回答？

### ISSUE THREAD

**Issue by orz12** [CLOUDERHEM/Zhiliao#2]

**Comment by CLOUDERHEM** [comment]
可以截图示意一下。知乎UI有几套，最新的可能已经处理部分了。

**Comment by orz12** [comment]
比如说
![Screenshot_2024-02-15-16-25-04-773_com zhihu android](https://github.com/CLOUDERHEM/Zhiliao/assets/17450420/1f933b1d-b566-4bba-9f78-a18884b7a670)

**Comment by CLOUDERHEM** [comment]
1. 知乎新UI中, 大部分广告文章是可以去除的, [详见(暂没有release)](https://github.com/CLOUDERHEM/Zhiliao/blob/0a8985213c3b9f3ac9e8693e588455905122e5b0/app/src/main/java/com/shatyuka/zhiliao/hooks/CustomFilterDataflow.java)
2. 旧UI中, 暂时没写(你目前使用就是旧UI)
3. 后续再研究一下怎样比较好的去除问题中的文章

**Comment by orz12** [comment]
哪个是新ui，是指全文视图吗？我感觉那个翻页比较卡顿（到下个回答的时候会只露出一部分，需要再额外拉一次），就没有用

**Comment by CLOUDERHEM** [comment]
> 旧
<img src="https://github.com/CLOUDERHEM/Zhiliao/assets/78064276/a6936a09-bc9f-4951-8f28-8ed1e094a1c8" width="251px">

----

> 新
<img src="https://github.com/CLOUDERHEM/Zhiliao/assets/78064276/901431ed-a9b4-4a49-97b2-a5eb13bb59cd" width="251px">

**Comment by orz12** [comment]
确实有差异，不过我好像没有找到对应的设置，切换卡片视图和全文视图都没有这个效果。会不会和我用的是play版本有关系

**Comment by CLOUDERHEM** [comment]
可以尝试一下这个版本 [23.10.08.fix.4](https://github.com/CLOUDERHEM/Zhiliao/releases/tag/23.10.08.fix.4)

大部分的广告推广应该能去除. 一个问题回答看完之后, 会推其他的问题, 这个暂不处理
