### ISSUE TITLE
[功能建议] 优化“知了：xxx功能加载失败”的Toast通知

### ISSUE THREAD

**Issue by qinxs** [CLOUDERHEM/Zhiliao#3]
知乎 [ v8.52.0.apk版 ](https://www.wandoujia.com/apps/584215/history) 使用 Zhiliao_23.10.08.fix.4 后
每次重启都会显示这个Toast通知 但这几个功能都是正常的

https://github.com/CLOUDERHEM/Zhiliao/assets/13647698/f71e60b2-cc12-4aeb-9443-ee53a42b5429

另外，建议在每次修改了知了配置后 才显示这个Toast通知
https://github.com/shatyuka/Zhiliao/issues/81

**Comment by iTeraxo** [comment]
附议

**Comment by CLOUDERHEM** [comment]
目前设置的是： 更新zhihu或者zhiliao后会提示一次
