### ISSUE TITLE
原版更新了

### ISSUE THREAD

**Issue by TCOTC** [CLOUDERHEM/Zhiliao#5]
https://github.com/shatyuka/Zhiliao/releases

**Comment by CLOUDERHEM** [comment]
https://github.com/shatyuka/Zhiliao/pull/112

**Comment by TCOTC** [comment]
@CLOUDERHEM 我是看到原版更新了，明确说明「兼容知乎9.41.0」，所以想问问原版更新前最近的那几个 Commits 有没有跟进（这个 [PR](https://github.com/shatyuka/Zhiliao/pull/112) 我有看到，但已经是上星期合并的了，所以想对比一下最新的 Commits ，但是两个仓库的 Commits 不同，我不太懂怎么比较）。如果这个 fork 版本也「兼容知乎9.41.0」，那我就准备升级了。

**Comment by TCOTC** [comment]
另外这个 fork 跟上游同步吗？

**Comment by CLOUDERHEM** [comment]
https://github.com/CLOUDERHEM/Zhiliao/compare/master...shatyuka%3AZhiliao%3Amaster

必要功能同步

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
